// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mr-chelyshkin/scrumble/internal/config"
	"github.com/mr-chelyshkin/scrumble/internal/daemon"
	"github.com/mr-chelyshkin/scrumble/internal/http_router"
	"github.com/mr-chelyshkin/scrumble/internal/logger"
	"github.com/mr-chelyshkin/scrumble/internal/stat"
)

// Injectors from wire.go:

func Init(cfg config.Config) (daemon.Daemon, func(), error) {
	context, cleanup := daemon.ProvideContext()
	loggerConfig, err := logger.ProvideConfig()
	if err != nil {
		cleanup()
		return daemon.Daemon{}, nil, err
	}
	zapLogger, err := logger.ProvideLoggerZap(loggerConfig)
	if err != nil {
		cleanup()
		return daemon.Daemon{}, nil, err
	}
	statConfig, err := stat.ProvideConfig()
	if err != nil {
		cleanup()
		return daemon.Daemon{}, nil, err
	}
	probe := http_router.ProvideProbe()
	statStat := stat.ProvideStat(statConfig, zapLogger, probe)
	daemonConfig, err := daemon.ProvideConfig()
	if err != nil {
		cleanup()
		return daemon.Daemon{}, nil, err
	}
	http_routerConfig, err := http_router.ProvideConfig()
	if err != nil {
		cleanup()
		return daemon.Daemon{}, nil, err
	}
	service := http_router.ProvideHttpRouter(http_routerConfig, zapLogger)
	daemonDaemon := daemon.ProvideDaemon(context, zapLogger, statStat, daemonConfig, service)
	return daemonDaemon, func() {
		cleanup()
	}, nil
}
